export type Language = 'EN' | 'NL' | 'FR' | 'DE' | 'ES';

export const translations: Record<Language, any> = {
  NL: {
    nav: { about: "Over Ons", services: "Diensten", why: "Waarom H&O?", cases: "Portfolio", quote: "Offerte Aanvragen" },
    hero: { spoc: "Supply Chain & Merchandise Partner", p1: "H&O Worldwide ", p2: "optimaliseert", p3: " uw merkvisibiliteit.", desc: "Wij ontwerpen en produceren hoogwaardige merchandise-oplossingen waarbij we de volledige logistieke keten overnemen. Efficiëntie en ontzorging voor corporates en premium merken.", quote: "Offerte Aanvragen", samplePack: "Vraag een Sample Pack aan", discover: "Bekijk de voordelen" },
    about: { title: "Van idee naar fysiek premium product, zonder zorgen.", p1: "Grote organisaties hebben geen behoefte aan een standaard catalogus. Ze zoeken een strategische partner die de merkidentiteit feilloos vertaalt naar tastbare producten en de volledige executie overneemt.", p2: "Door de inzet van in-house designers en krachtige productiehubs in Turkije en China zorgen wij voor oplossingen die niet alleen esthetisch perfect zijn, maar ook schaalbaar en conform alle internationale normen.", p3: "Wij nemen de volledige logistieke keten over. U behoudt de regie, wij doen het werk.", stat1: "100%", stat2: "Ontzorging &\nCompliance Garantié" },
    services: { subtitle: "Onze Expertise", title: "End-to-End Sourcing Oplossingen", viewAll: "Bekijk Alle Mogelijkheden",
      s1: { title: "Custom Made Productie", desc: "Volledig maatwerk dat aansluit bij uw brand guidelines. Van de exacte Pantone™ PMS-kleuren tot doordachte materiaalkeuze voor een premium positionering.", longTitle: "De diepgang: Van visie naar tastbaar resultaat.", longDesc: "Bij H&O Worldwide geloven we dat standaardoplossingen zelden de essentie van een premium merk vangen. Onze 'Custom Made' aanpak begint bij het begrijpen van uw merk-DNA. Wij werken niet met standaard catalogusartikelen, maar bouwen producten vanaf de basis op.\n\nDit betekent dat we exact matchen op uw Pantone™ PMS-kleuren voor een consistente merkuitstraling wereldwijd. We adviseren proactief in materiaalgebruik — van duurzame rPET-stoffen tot hoogwaardig geborsteld metaal — om de gewenste tactiele ervaring te creëren die aansluit bij uw marktpositionering. Uw merkrichtlijnen zijn onze blauwdruk voor elk detail, van stiksel tot verpakking." },
      s2: { title: "Strategische Hubs", desc: "Onze focus-zones: Turkije voor hoogwaardig textiel en ultra-snelle levering (near-shoring), China voor technologische gadgets en maximale schaalvoordelen.", longTitle: "De diepgang: Wereldwijd bereik, lokale expertise.", longDesc: "Onze logistieke infrastructuur is gebouwd op twee pijlers: snelheid en schaal.\n\nTurkije (Premium Textiles & Speed): Onze hubs in Turkije zijn gespecialiseerd in hoogwaardig textiel. Door de geografische nabijheid van Europa bieden we hier 'ultra-fast near-shoring'. Dit stelt ons in staat om complexe textielprojecten binnen recordtijd te produceren en te leveren, ideaal voor tijdgevoelige campagnes.\n\nChina (Tech & Scale): Voor technologische innovaties en enorme volumes maken we gebruik van onze gevestigde partnerschappen in China. Hier realiseren we maximale schaalvoordelen voor tech-gadgets en complexe hardware, zonder in te leveren op de strengste kwaliteitscontroles.\n\nDoor deze hybride strategie bieden we altijd de meest efficiënte route voor uw specifieke project." },
      s3: { title: "Full-Service Logistiek", desc: "Efficiëntie is key. Na de productiefase dragen wij zorg voor QC, douane-afhandeling, warehousing en de uiteindelijke last-mile delivery.", longTitle: "De diepgang: Volledige ontzorging, van fabriek tot bureau.", longDesc: "Productie is slechts de helft van het verhaal; de echte uitdaging zit in de executie. H&O neemt de volledige operationele last uit uw handen. Zodra de productie is afgerond, start ons integrale logistieke proces:\n\nQuality Control (QC): Onafhankelijke inspecties ter plaatse voordat er ook maar iets wordt verscheept.\n\nCustoms & Compliance: Wij regelen alle douaneformaliteiten, invoerrechten en complexe documentatie.\n\nWarehousing: Indien nodig slaan we uw voorraad veilig op in onze strategische verdeelcentra.\n\nLast-Mile Delivery: Of het nu gaat om levering bij één centraal distributiecentrum of op 500 individuele kantooradressen wereldwijd: wij zorgen dat het pakket op het juiste moment in de juiste handen terechtkomt." },
      s4: { title: "Kwaliteit & Ethiek", desc: "Absolute compliance-zekerheid. Al onze partnerfabrieken opereren volgens strikte EU-normen (incl. CE-markeringen) en strikte sociale audits.", longTitle: "De diepgang: Integriteit als fundament.", longDesc: "In de huidige zakelijke wereld is compliance geen optie, maar een vereiste. Wij beschermen uw reputatie door alleen samen te werken met fabrieken die voldoen aan de hoogste ethische en technische standaarden.\n\nAl onze hardware is volledig CE-gecertificeerd en voldoet aan de strengste EU-veiligheidsnormen (zoals RoHS en REACH). Daarnaast ondergaan onze partner-fabrieken periodieke sociale audits (zoals Sedex of BSCI) om eerlijke arbeidsomstandigheden, veiligheid op de werkvloer en milieubewuste productieprocessen te garanderen. Bij H&O Worldwide krijgt u niet alleen een premium product, maar ook de absolute zekerheid dat het geproduceerd is met respect voor mens en planeet." }
    },
    nodes: { title: "Strategische Sourcing Nodes", desc: "Kies de supply chain blueprint die past bij uw missie.",
      tr: { title: "Hub Turkije", features: ["Focus: Duurzame Mode & Textiel", "Transport: Truck (Eco-vriendelijker)", "Lead-time: 2-3 weken", "Specialiteit: Snelheid & Near-Shoring"] },
      cn: { title: "Hub China", features: ["Focus: Tech-gadgets & Volume", "Transport: Zee- & Luchtvracht", "Lead-time: 8-12 weken", "Specialiteit: Schaal & Kostenefficiëntie"] }
    },
    journey: { title: "De H&O Journey", desc: "Onze waterdichte A-Z logistieke executie.",
      steps: [
        { title: "Conceptueel Design", desc: "Merkidentiteit vertalen naar tastbare premiums." },
        { title: "Node Routing", desc: "Keuze van de logistieke hub (Turkije vs China)." },
        { title: "Productie & Kwaliteit", desc: "Ethical manufacturing met AQL inspecties." },
        { title: "Last-Mile Delivery", desc: "Douane-afhandeling en drempellevering." }
      ]
    },
    cases: { subtitle: "Concept Cases", title: "Premium oplossingen, tastbaar gemaakt", 
      items: [
        { title: "Executive Onboarding Experience", desc: "Luxe 'Welcome-to-the-team' pakketten die de corporate identiteit feilloos vertalen naar een tastbaar moment van waardering voor nieuw talent.", longDesc: "Ontworpen voor high-level partners die streven naar een onvergetelijke eerste indruk. Deze executive boxen bevatten premium Moleskine-stijl notitieboeken, hoogwaardige schrijfwaren en gepersonaliseerde tech-essentials zoals bespoke powerbanks. Elk element wordt met zorg geselecteerd om de waarden en professionaliteit van uw kantoor te reflecteren, volledig ontzorgd van design tot distributie." },
        { title: "Premium Tech Event Solutions", desc: "Duurzame merkactivatie voor de tech-sector: hoogwaardige rPET-rugzakken gecombineerd met gecertificeerde innovatieve hardware.", longDesc: "Maak impact op uw volgende event met swag die écht wordt gebruikt. Wij combineren ecologisch verantwoorde rPET-rugzakken met top-tier, CE-gecertificeerde wireless fast-chargers. Onze full-service aanpak garandeert directe levering op de eventlocatie, waarbij technische perfectie en duurzaamheid hand in hand gaan. Ideaal voor grootschalige internationale tech-conferenties waar kwaliteit de norm is." },
        { title: "National Brand Activation", desc: "Grootschalige productie en razendsnelle 'fast-track' levering van merk-activatie kits voor landelijke marketingcampagnes.", longDesc: "Maximaliseer uw marktpenetratie met hoogwaardige consumentenproducten. Voor deze case leverden wij volumeprojecten van custom terry cloth handdoeken en premium koeltassen. Dankzij onze strategische productie-hubs in Turkije garanderen wij een extreem korte time-to-market, zelfs bij volumes van 10.000+ units. Wij beheren de volledige keten: van Pantone-matching tot de uiteindelijke last-mile delivery bij uw distributeurs." }
      ]
    },
    why: { title: "De H&O Garantie", desc: "Waarom grote spelers ons hun promotionele inkoop en distributie toevertrouwen.",
      features: [
        { title: "Ontzorging van A tot Z", desc: "Wij elimineren de complexiteit. Geen kopzorgen over importheffingen, defecten of communicatie. Wij zijn uw dedicated SPOC.", longTitle: "De diepgang: Uw dedicated partner in een complexe wereld.", longDesc: "Het inkoopproces van custom merchandise is vaak een mijnenveld van logistieke uitdagingen en administratieve rompslomp. H&O fungeert als uw schild. Wij nemen de volledige verantwoordelijkheid voor het traject: van het eerste ontwerp en de kwaliteitscontrole in de fabriek tot het regelen van complexe importheffingen en douaneformaliteiten.\n\nU heeft geen omkijken naar defecten of miscommunicatie met leveranciers in andere tijdzones. Als uw Single Point of Contact (SPOC) bieden wij volledige transparantie en rust, zodat u zich kunt focussen op uw kernactiviteiten terwijl wij de tastbare resultaten leveren." },
        { title: "Transparante Schaalvoordelen", desc: "We elimineren de tussenlaag. Onze directe inkoop en volume bundling garanderen de scherpste procurement-voorwaarden.", longTitle: "De diepgang: Directe inkoopkracht zonder verborgen kosten.", longDesc: "Grote volumes vereisen een scherpe blik op de kostenstructuur. Omdat H&O de traditionele tussenlagen (zoals agenten en lokale groothandels) elimineert, koopt u direct in bij de bron. We bundelen onze inkoopvolumes strategisch om de scherpste procurement-voorwaarden af te dwingen voor onze klanten.\n\nDeze efficiëntie vertalen we naar een transparant prijsmodel. Geen verborgen marges op transport of onduidelijke opslagen voor douaneafhandeling. U profiteert van de schaal van een wereldspeler met de persoonlijke aandacht van een boutique bureau. Wij bewijzen dat premium kwaliteit en een gezonde bottom-line uitstekend samen kunnen gaan." },
        { title: "Europese Compliance en Kwaliteit", desc: "Van CE-markeringen op elektronica tot BSCI-gecertificeerde kleding, wij leveren 100% veiligheid aan uw inkoopafdeling.", longTitle: "De diepgang: Veiligheid voor uw merk en uw eindgebruiker.", longDesc: "Voor een merk is niets zo schadelijk als een onveilig product of een ethisch dubieuze productieketen. De H&O Garantie betekent dat elk product dat wij leveren voldoet aan de strengste Europese wetgeving.\n\nOf het nu gaat om de elektrische veiligheid van een charger (CE-markering), de afwezigheid van schadelijke stoffen in textiel (REACH/OEKO-TEX) of de sociale omstandigheden in de fabriek (BSCI/Sedex audits): wij leveren 100% veiligheid aan uw inkoopafdeling. Wij voeren onafhankelijke tests uit om te garanderen dat de geleverde kwaliteit exact overeenkomt met het goedgekeurde sample. Uw merkwaardigheid is bij ons in veilige handen.", showBadges: true },
        { title: "Snelheid (Near-Shoring)", desc: "Via onze Turkse textielcentra kunnen we ongekend snel schakelen wanneer er onmiddellijk op markttrends gereageerd moet worden.", longTitle: "De diepgang: Wendbaarheid in een veranderende markt.", longDesc: "In de moderne marketingwereld is 'snelheid' vaak de bepalende factor voor succes. Lange wachttijden uit Azië zijn niet altijd een optie wanneer u direct wilt inspelen op een markttrend of een last-minute event.\n\nOnze strategische focus op Near-Shoring via onze Turkse textielcentra stelt ons in staat om de doorlooptijden drastisch te verkorten. Terwijl transport over zee vanuit het Verre Oosten weken in beslag neemt, kunnen wij via wegtransport vanuit Turkije binnen enkele dagen leveren in de Benelux. Dit geeft u de flexibiliteit om korter op de bal te spelen, voorraden lager te houden en sneller te schakelen zonder in te boeten op de kwaliteit van de afwerking." }
      ]
    },
    break: "Schaalbare oplossingen. Zonder kwaliteitsverlies.",
    contact: { ready: "Uw logistieke keten vereenvoudigen?", title: "Elevate your corporate gifting.", desc: "Contacteer onze Senior Account Managers om te bespreken hoe H&O Worldwide uw promotionele efficiëntie kan verhogen.", quote: "Vraag een Sample Pack aan", call: "Contacteer Ons" },
    footer: { desc: "H&O Worldwide Solutions is uw B2B partner in custom sourcing, ethical production en full-service merchandise logistics.", menu: "Navigatie", offices: "Operationele Hubs", hq: "Hoofdkantoor EU", privacy: "Privacybeleid & Cookies", certs: "Compliance Garantie door:" },
    cookie: { title: "Wij respecteren uw privacy", desc: "We gebruiken noodzakelijke cookies om de website goed te laten werken. Daarnaast gebruiken we optionele cookies voor analytische doeleinden om onze dienstverlening te verbeteren. Door op 'Weigeren' te klikken worden alleen noodzakelijke cookies geplaatst.", accept: "Beide Accepteren", reject: "Weiger Optioneel" }
  },
  EN: {
    nav: { about: "About Us", services: "Services", why: "Why H&O?", cases: "Portfolio", quote: "Request Quote" },
    hero: { spoc: "Supply Chain & Merchandise Partner", p1: "H&O Worldwide ", p2: "optimizes", p3: " your brand visibility.", desc: "We design and produce high-end merchandise solutions while taking over the entire logistics chain. Efficiency and unburdening for corporates and premium brands.", quote: "Request Quote", samplePack: "Request a Sample Pack", discover: "Discover the benefits" },
    about: { title: "From concept to premium physical product, hassle-free.", p1: "Large organizations do not need a standard catalog. They seek a strategic partner that translates their brand identity into tangible products seamlessly.", p2: "By deploying in-house designers and powerful production hubs in Turkey and China, we ensure solutions that are aesthetically perfect, scalable, and fully compliant with international norms.", p3: "We take full control of the supply chain. You keep the direction, we do the work.", stat1: "100%", stat2: "Unburdening &\nCompliance Guarantee" },
    services: { subtitle: "Our Expertise", title: "End-to-End Sourcing Solutions", viewAll: "View All Options",
      s1: { title: "Custom Made Production", desc: "Fully tailored to your brand guidelines. From exact Pantone™ PMS-matching to deliberate material choices for premium positioning.", longTitle: "In Depth: From vision to tangible result.", longDesc: "At H&O Worldwide we believe that standard solutions rarely capture the essence of a premium brand. Our 'Custom Made' approach starts with understanding your brand DNA. We don't work with standard catalog items, but build products from the ground up.\n\nThis means exactly matching your Pantone™ PMS colors for a consistent brand image worldwide. We pro-actively advise on material use — from sustainable rPET fabrics to high-quality brushed metal — to create the desired tactile experience aligning with your market positioning. Your brand guidelines are our blueprint for every detail, from stitching to packaging." },
      s2: { title: "Strategic Hubs", desc: "Our core areas: Turkey for premium textiles and ultra-fast near-shoring, China for tech gadgets and maximum economies of scale.", longTitle: "In Depth: Global reach, local expertise.", longDesc: "Our logistics infrastructure is built on two pillars: speed and scale.\n\nTurkey (Premium Textiles & Speed): Our hubs in Turkey specialize in high-quality textiles. Due to geographical proximity to Europe, we offer 'ultra-fast near-shoring' here. This allows us to produce and deliver complex textile projects in record time, ideal for time-sensitive campaigns.\n\nChina (Tech & Scale): For technological innovations and huge volumes, we leverage our established partnerships in China. Here we realize maximum economies of scale for tech gadgets and complex hardware, without compromising on the strictest quality controls.\n\nThrough this hybrid strategy, we always offer the most efficient route for your specific project." },
      s3: { title: "Full-Service Logistics", desc: "Efficiency is key. Post-production, we handle QC, customs clearance, warehousing, and the ultimate last-mile delivery.", longTitle: "In Depth: Complete unburdening, from factory to desk.", longDesc: "Production is only half the story; the real challenge lies in the execution. H&O takes the full operational burden off your hands. Once production is complete, our integrated logistics process starts:\n\nQuality Control (QC): Independent on-site inspections before anything is shipped at all.\n\nCustoms & Compliance: We handle all customs formalities, import duties, and complex documentation.\n\nWarehousing: If necessary, we safely store your inventory in our strategic distribution centers.\n\nLast-Mile Delivery: Whether delivering to one central distribution center or 500 individual office addresses worldwide: we ensure the package reaches the right hands at the right time." },
      s4: { title: "Quality & Ethics", desc: "Absolute compliance security. All partner factories conform to strict EU standards (including CE) and pass strict social audits.", longTitle: "In Depth: Integrity as a foundation.", longDesc: "In today's business world, compliance is not an option, but a requirement. We protect your reputation by only partnering with factories that meet the highest ethical and technical standards.\n\nAll our hardware is fully CE certified and meets the strictest EU safety standards (such as RoHS and REACH). In addition, our partner factories undergo periodic social audits (like Sedex or BSCI) to ensure fair working conditions, workplace safety, and environmentally conscious production processes. With H&O Worldwide, you not only get a premium product, but also the absolute certainty that it is produced with respect for people and the planet." }
    },
    nodes: { title: "Strategic Sourcing Nodes", desc: "Choose the supply chain blueprint that fits your mission.",
      tr: { title: "Hub Turkey", features: ["Focus: Sustainable Fashion & Textiles", "Transport: Truck (Eco-friendlier)", "Lead-time: 2-3 weeks", "Specialty: Speed & Near-Shoring"] },
      cn: { title: "Hub China", features: ["Focus: Tech-gadgets & Volume", "Transport: Sea & Airfreight", "Lead-time: 8-12 weeks", "Specialty: Scale & Cost efficiency"] }
    },
    journey: { title: "The H&O Journey", desc: "Our airtight A-Z logistics pipeline.",
      steps: [
        { title: "Conceptual Design", desc: "Translating brand identity into physical premiums." },
        { title: "Node Routing", desc: "Choosing the strategic hub (Turkey vs China)." },
        { title: "Production & QC", desc: "Ethical manufacturing with strict AQL inspections." },
        { title: "Last-Mile Delivery", desc: "Customs clearance and doorstep delivery." }
      ]
    },
    cases: { subtitle: "Portfolio", title: "Premium solutions, made tangible", 
      items: [
        { title: "Executive Onboarding Experience", desc: "Luxury 'Welcome-to-the-team' packages that flawlessly translate corporate identity into a tangible moment of appreciation for new talent.", longDesc: "Designed for high-level partners striving for an unforgettable first impression. These executive boxes contain premium Moleskine-style notebooks, high-quality writing instruments, and personalized tech essentials such as bespoke power banks. Each element is carefully selected to reflect the values and professionalism of your firm, fully managed from design to distribution." },
        { title: "Premium Tech Event Solutions", desc: "Sustainable brand activation for the tech sector: high-quality rPET backpacks combined with certified innovative hardware.", longDesc: "Make an impact at your next event with swag that actually gets used. We combine ecologically responsible rPET backpacks with top-tier, CE-certified wireless fast chargers. Our full-service approach guarantees direct delivery to the event location, where technical perfection and sustainability go hand in hand. Ideal for large-scale international tech conferences where quality is the standard." },
        { title: "National Brand Activation", desc: "Large-scale production and lightning-fast track delivery of brand activation kits for nationwide marketing campaigns.", longDesc: "Maximize your market penetration with high-quality consumer products. For this case, we delivered volume projects of custom terry cloth towels and premium cooler bags. Thanks to our strategic production hubs in Turkey, we guarantee an extremely short time-to-market, even with volumes of 10,000+ units. We manage the entire chain: from Pantone matching to the final last-mile delivery to your distributors." }
      ]
    },
    why: { title: "The H&O Guarantee", desc: "Why major players entrust us with their promotional procurement and distribution.",
      features: [
        { title: "End-to-End Unburdening", desc: "We eliminate complexity. No concerns about import duties, flaws, or communication. We are your dedicated SPOC.", longTitle: "In Depth: Your dedicated partner in a complex world.", longDesc: "The procurement process of custom merchandise is often a minefield of logistical challenges and administrative red tape. H&O acts as your shield. We take full responsibility for the entire trajectory: from the initial design and quality control in the factory to arranging complex import duties and customs formalities.\n\nYou do not have to worry about defects or miscommunication with suppliers in other time zones. As your Single Point of Contact (SPOC), we offer full transparency and peace of mind, so you can focus on your core activities while we deliver the tangible results." },
        { title: "Transparent Economies of Scale", desc: "We cut out the middleman. Our direct purchasing and volume bundling guarantee sharp procurement rates.", longTitle: "In Depth: Direct purchasing power without hidden costs.", longDesc: "Large volumes require a sharp eye on the cost structure. Because H&O eliminates traditional intermediaries (such as agents and local wholesalers), you buy directly from the source. We strategically bundle our purchasing volumes to enforce the sharpest procurement conditions for our clients.\n\nWe translate this efficiency into a transparent pricing model. No hidden margins on transport or unclear surcharges for customs clearance. You benefit from the scale of a global player with the personal attention of a boutique agency. We prove that premium quality and a healthy bottom line can go hand in hand perfectly." },
        { title: "European Compliance & Quality", desc: "From CE marks on electronics to BSCI-certified clothing, we guarantee 100% safety and peace of mind for your purchasing department.", longTitle: "In Depth: Security for your brand and your end user.", longDesc: "Nothing is as damaging to a brand as an unsafe product or an ethically dubious production chain. The H&O Guarantee means that every product we deliver complies with the strictest European legislation.\n\nWhether it concerns the electrical safety of a charger (CE marking), the absence of harmful substances in textiles (REACH/OEKO-TEX) or the social conditions in the factory (BSCI/Sedex audits): we deliver 100% safety to your purchasing department. We carry out independent tests to guarantee that the delivered quality exactly matches the approved sample. Your brand integrity is in safe hands with us.", showBadges: true },
        { title: "Speed (Near-Shoring)", desc: "Through our Turkish textile hubs, we can act remarkably fast when instant market trend reactions are required.", longTitle: "In Depth: Agility in a changing market.", longDesc: "In the modern marketing world, 'speed' is often the determining factor for success. Long waiting times from Asia are not always an option when you want to respond immediately to a market trend or a last-minute event.\n\nOur strategic focus on Near-Shoring via our Turkish textile hubs allows us to drastically reduce lead times. While sea transport from the Far East takes weeks, we can deliver to the Benelux within a few days via road transport from Turkey. This gives you the flexibility to be more responsive, keep inventory lower, and move faster without compromising on the quality of the finish." }
      ]
    },
    break: "Scalable solutions. Zero compromises.",
    contact: { ready: "Ready to simplify your supply chain?", title: "Elevate your corporate gifting.", desc: "Contact our Senior Account Managers to discuss how H&O Worldwide can elevate your promotional efficiency.", quote: "Request a Sample Pack", call: "Contact Us" },
    footer: { desc: "H&O Worldwide Solutions is your B2B partner in custom sourcing, ethical production, and full-service merchandise logistics.", menu: "Navigation", offices: "Operational Hubs", hq: "Headquarters EU", privacy: "Privacy Policy & Cookies", certs: "Compliance Guarantee by:" },
    cookie: { title: "We respect your privacy", desc: "We use essential cookies to make our site work. We also use optional cookies for analytics to improve our services. By clicking 'Reject', only strictly necessary cookies will be set.", accept: "Accept All", reject: "Reject Optional" }
  },
  FR: {
    nav: { about: "À Propos", services: "Services", why: "Pourquoi H&O?", cases: "Portfolio", quote: "Demander Devis" },
    hero: { spoc: "Partenaire Supply Chain & Marchandises", p1: "H&O Worldwide ", p2: "optimise", p3: " la visibilité de votre marque.", desc: "Nous concevons et produisons des solutions de marchandises haut de gamme tout en prenant en charge l'ensemble de la chaîne logistique. Efficacité pour les grandes entreprises et marques premium.", quote: "Demander un Devis", samplePack: "Demander un Pack Échantillon", discover: "Découvrez les avantages" },
    about: { title: "De l'idée au produit physique de qualité supérieure, sans tracas.", p1: "Les grandes organisations ne recherchent pas un catalogue standard. Elles cherchent un partenaire stratégique qui traduit parfaitement leur identité en produits tangibles.", p2: "Grâce à nos designers internes et nos puissants centres de production en Turquie et en Chine, nous assurons des solutions esthétiquement parfaites, évolutives et entièrement conformes aux normes internationales.", p3: "Nous contrôlons toute la chaîne logistique. Vous gardez la direction, nous faisons le reste.", stat1: "100%", stat2: "Garantie de Sérénité &\nConformité" },
    services: { subtitle: "Notre Expertise", title: "Solutions de Sourcing de A à Z", viewAll: "Voir toutes les options",
      s1: { title: "Production Sur-Mesure", desc: "Entièrement adapté à vos directives de marque. Du respect exact des couleurs Pantone™ PMS au choix des matériaux pour un positionnement premium.", longTitle: "En profondeur: De la vision au résultat tangible.", longDesc: "Chez H&O Worldwide, nous croyons que les solutions standard capturent rarement l'essence d'une marque premium. Notre approche 'Sur-Mesure' commence par la compréhension de l'ADN de votre marque. Nous ne travaillons pas avec des articles de catalogue standard, mais construisons les produits de zéro.\n\Cela signifie correspondre exactement à vos couleurs Pantone™ PMS pour une image de marque cohérente dans le monde entier. Nous conseillons de manière proactive sur l'utilisation des matériaux — des tissus rPET durables au métal brossé de haute qualité — pour créer l'expérience tactile souhaitée qui s'aligne avec votre positionnement sur le marché. Les directives de votre marque sont notre plan pour chaque détail, des coutures à l'emballage." },
      s2: { title: "Hubs Stratégiques", desc: "Nos zones clés: la Turquie pour des textiles de qualité et un near-shoring ultra-rapide, la Chine pour les gadgets technologiques et des économies d'échelle maximales.", longTitle: "En profondeur: Portée mondiale, expertise locale.", longDesc: "Notre infrastructure logistique repose sur deux piliers: la vitesse et l'échelle.\n\nTurquie (Textiles Premium & Vitesse): Nos hubs en Turquie sont spécialisés dans les textiles de haute qualité. En raison de la proximité géographique avec l'Europe, nous y proposons un 'near-shoring ultra-rapide'. Cela nous permet de produire et de livrer des projets textiles complexes en un temps record, idéal pour des campagnes urgentes.\n\nChine (Tech & Échelle): Pour les innovations technologiques et les volumes énormes, nous nous appuyons sur nos partenariats établis en Chine. C'est ici que nous réalisons des économies d'échelle maximales pour les gadgets technologiques et le matériel complexe, sans compromis sur les contrôles de qualité les plus stricts.\n\nGrâce à cette stratégie hybride, nous offrons toujours l'itinéraire le plus efficace pour votre projet spécifique." },
      s3: { title: "Logistique Complète", desc: "L'efficacité est primordiale. Après la production, nous gérons le contrôle qualité (QC), le dédouanement, l'entreposage et la livraison finale.", longTitle: "En profondeur: Soulagement complet, de l'usine au bureau.", longDesc: "La production n'est que la moitié de l'histoire; le vrai défi réside dans l'exécution. H&O vous décharge entièrement du fardeau opérationnel. Une fois la production terminée, notre processus logistique intégré commence:\n\nContrôle de la qualité (QC): Inspections indépendantes sur site avant tout envoi.\n\nDouanes & Conformité: Nous gérons toutes les formalités douanières, les droits d'importation et la documentation complexe.\n\nEntreposage: Si nécessaire, nous stockons votre inventaire en toute sécurité dans nos centres de distribution stratégiques.\n\nLivraison Finale: Qu'il s'agisse d'une livraison dans un centre de distribution centralisé ou à 500 adresses professionnelles distinctes : nous veillons à ce que le colis arrive entre de bonnes mains au bon moment." },
      s4: { title: "Qualité & Éthique", desc: "Sécurité absolue de conformité. Nos usines partenaires respectent les normes strictes de l'UE (y compris CE) et réussissent des audits sociaux rigoureux.", longTitle: "En profondeur: L'intégrité comme fondement.", longDesc: "Dans le monde des affaires d'aujourd'hui, la conformité n'est pas une option, mais une exigence. Nous protégeons votre réputation en nous associant uniquement avec des usines respectant les normes éthiques et techniques les plus élevées.\n\nL'ensemble de notre matériel est entièrement certifié CE et répond aux normes de sécurité les plus strictes de l'UE (telles que RoHS et REACH). De plus, nos usines partenaires subissent des audits sociaux périodiques (comme Sedex ou BSCI) pour garantir des conditions de travail équitables, la sécurité au travail et des processus de production respectueux de l'environnement. Avec H&O Worldwide, vous obtenez non seulement un produit haut de gamme, mais aussi la certitude absolue qu'il a été produit dans le respect des personnes et de la planète." }
    },
    nodes: { title: "Noeuds de Sourcing Stratégiques", desc: "Choisissez la logistique qui correspond à votre mission.",
      tr: { title: "Hub Turquie", features: ["Mise au point: Mode Durable & Textiles", "Transport: Camion (Plus Écologique)", "Délai de Livraison: 2-3 semaines", "Spécialité: Vitesse & Near-Shoring"] },
      cn: { title: "Hub Chine", features: ["Mise au point: Gadgets & Volume", "Transport: Fret Maritime & Aérien", "Délai de Livraison: 8-12 semaines", "Spécialité: Échelle & Efficacité des Coûts"] }
    },
    journey: { title: "Le Parcours H&O", desc: "Notre exécution logistique infaillible de A à Z.",
      steps: [
        { title: "Design Conceptuel", desc: "Traduire l'identité de marque en primes tangibles." },
        { title: "Routage des Nœuds", desc: "Choix du hub stratégique (Turquie ou Chine)." },
        { title: "Production & QC", desc: "Fabrication éthique avec des inspections AQL strictes." },
        { title: "Livraison Finale", desc: "Dédouanement et livraison à domicile." }
      ]
    },
    cases: { subtitle: "Portfolio", title: "Des solutions premium, rendues tangibles", 
      items: [
        { title: "Expérience d'Intégration Exécutive", desc: "Des packages 'Welcome-to-the-team' de luxe qui traduisent parfaitement l'identité de l'entreprise en un moment d'appréciation tangible pour les nouveaux talents.", longDesc: "Conçus pour les partenaires de haut niveau qui visent une première impression inoubliable. Ces boîtes exécutives contiennent des carnets de notes premium de style Moleskine, des instruments d'écriture de haute qualité et des accessoires technologiques personnalisés, tels que des batteries externes sur mesure. Chaque élément est soigneusement sélectionné pour refléter les valeurs et le professionnalisme de votre cabinet, avec une gestion complète de la conception à la distribution." },
        { title: "Solutions Événementielles Tech Premium", desc: "Activation de marque durable pour le secteur technologique : sacs à dos en rPET de haute qualité combinés à du matériel innovant certifié.", longDesc: "Faites impression lors de votre prochain événement avec des cadeaux promotionnels (swag) qui sont réellement utilisés. Nous combinons des sacs à dos en rPET écologiquement responsables avec des chargeurs rapides sans fil de premier ordre certifiés CE. Notre approche full-service garantit une livraison directe sur le lieu de l'événement, où perfection technique et durabilité vont de pair. Idéal pour les grandes conférences technologiques internationales où la qualité est la norme." },
        { title: "Activation de Marque Nationale", desc: "Production à grande échelle et livraison ultra-rapide de kits d'activation de marque pour des campagnes marketing nationales.", longDesc: "Maximisez votre pénétration du marché avec des produits de consommation de haute qualité. Pour ce projet, nous avons livré des volumes importants de serviettes éponge personnalisées et de sacs isothermes premium. Grâce à nos hubs de production stratégiques en Turquie, nous garantissons un délai de mise sur le marché extrêmement court, même pour des volumes de plus de 10 000 unités. Nous gérons toute la chaîne : de la correspondance Pantone à la livraison finale du dernier kilomètre chez vos distributeurs." }
      ]
    },
    why: { title: "La Garantie H&O", desc: "Pourquoi les grands acteurs nous confient leurs achats promotionnels et leur distribution.",
      features: [
        { title: "Sérénité Totale", desc: "Nous éliminons la complexité. Pas de soucis pour les droits d'importation, les défauts ou la communication. Un point de contact unique (SPOC).", longTitle: "En profondeur : Votre partenaire dédié dans un monde complexe.", longDesc: "Le processus d'achat de marchandises personnalisées est souvent un champ de mines de défis logistiques et de formalités administratives. H&O agit comme votre bouclier. Nous prenons l'entière responsabilité de l'ensemble du processus : de la conception initiale et du contrôle qualité à l'usine au règlement des droits d'importation complexes et des formalités douanières.\n\nVous n'avez pas à vous soucier des défauts ou des problèmes de communication avec les fournisseurs dans d'autres fuseaux horaires. En tant que point de contact unique (SPOC), nous offrons une transparence et une tranquillité d'esprit totales, vous permettant de vous concentrer sur vos activités principales pendant que nous livrons des résultats tangibles." },
        { title: "Économies d'Échelle", desc: "Nous éliminons les intermédiaires. Nos achats directs garantissent des tarifs très compétitifs.", longTitle: "En profondeur : Pouvoir d'achat direct sans coûts cachés.", longDesc: "Les gros volumes exigent une vision claire de la structure des coûts. Étant donné que H&O élimine les intermédiaires traditionnels (tels que les agents et les grossistes locaux), vous achetez directement à la source. Nous regroupons stratégiquement nos volumes d'achats pour imposer les meilleures conditions d'approvisionnement pour nos clients.\n\nNous traduisons cette efficacité en un modèle de tarification transparent. Pas de marges cachées sur le transport ni de suppléments peu clairs pour le dédouanement. Vous bénéficiez de l'envergure d'un acteur mondial avec l'attention personnelle d'une agence de proximité. Nous prouvons que la qualité premium et une rentabilité saine peuvent parfaitement aller de pair." },
        { title: "Conformité & Qualité", desc: "Des normes CE sur l'électronique aux vêtements certifiés BSCI, nous garantissons une sécurité totale pour vos achats.", longTitle: "En profondeur : Sécurité pour votre marque et votre utilisateur final.", longDesc: "Rien n'est aussi dommageable pour une marque qu'un produit dangereux ou qu'une chaîne de production douteuse sur le plan éthique. La garantie H&O signifie que chaque produit que nous livrons est conforme à la législation européenne la plus stricte.\n\nQu'il s'agisse de la sécurité électrique d'un chargeur (marquage CE), de l'absence de substances nocives dans les textiles (REACH/OEKO-TEX) ou des conditions sociales dans l'usine (audits BSCI/Sedex) : nous livrons une sécurité à 100% à votre département des achats. Nous effectuons des tests indépendants pour garantir que la qualité livrée correspond exactement à l'échantillon approuvé. L'intégrité de votre marque est entre de bonnes mains avec nous.", showBadges: true },
        { title: "Rapidité (Near-Shoring)", desc: "Via nos centres textiles turcs, nous réagissons très vite aux tendances du marché.", longTitle: "En profondeur : Agilité sur un marché en mutation.", longDesc: "Dans le monde du marketing moderne, la 'vitesse' est souvent le facteur déterminant du succès. De longs délais d'attente en provenance d'Asie ne sont pas toujours une option lorsque vous souhaitez réagir immédiatement à une tendance du marché ou à un événement de dernière minute.\n\nNotre focalisation stratégique sur le Near-Shoring via nos hubs textiles turcs nous permet de réduire considérablement les délais de livraison. Alors que le transport maritime depuis l'Extrême-Orient prend des semaines, nous pouvons livrer au Benelux en quelques jours par transport routier depuis la Turquie. Cela vous donne la flexibilité d'être plus réactif, de maintenir les stocks à un niveau bas et de vous adapter plus rapidement sans compromettre la qualité de la finition." }
      ]
    },
    break: "Solutions évolutives. Zéro compromis.",
    contact: { ready: "Prêt à simplifier votre supply chain?", title: "Élevez vos cadeaux d'entreprise.", desc: "Contactez nos gestionnaires pour discuter de la façon dont H&O Worldwide peut améliorer votre efficacité promotionnelle.", quote: "Demander un Sample Pack", call: "Contactez-Nous" },
    footer: { desc: "H&O Worldwide Solutions est votre partenaire B2B pour l'approvisionnement sur mesure, la production éthique et la logistique complète.", menu: "Navigation", offices: "Hubs Opérationnels", hq: "Siège de l'UE", privacy: "Politique de Confidentialité", certs: "Garantie de Conformité par:" },
    cookie: { title: "Nous respectons votre vie privée", desc: "Nous utilisons des cookies essentiels. Nous utilisons également des cookies optionnels pour l'analyse. En cliquant sur 'Rejeter', seuls les cookies nécessaires seront définis.", accept: "Tout Accepter", reject: "Rejeter (Optionnel)" }
  },
  DE: {
    nav: { about: "Über Uns", services: "Leistungen", why: "Warum H&O?", cases: "Portfolio", quote: "Angebot Anfragen" },
    hero: { spoc: "Supply Chain & Merchandise Partner", p1: "H&O Worldwide ", p2: "optimiert", p3: " Ihre Markensichtbarkeit.", desc: "Wir entwerfen und produzieren High-End-Merchandise-Lösungen und übernehmen die gesamte Logistikkette. Effizienz und Entlastung für Unternehmen und Premium-Marken.", quote: "Angebot Anfragen", samplePack: "Musterpaket Anfragen", discover: "Vorteile entdecken" },
    about: { title: "Von der Idee zum physischen Premiumprodukt, stressfrei.", p1: "Große Organisationen brauchen keine Standardkataloge. Sie suchen einen strategischen Partner, der ihre Markenidentität in greifbare Produkte übersetzt.", p2: "Durch unsere Inhouse-Designer und Produktionszentren in der Türkei und China garantieren wir absolut perfekte, skalierbare und standardkonforme Lösungen.", p3: "Wir kontrollieren die gesamte Lieferkette. Sie behalten die Führung, wir erledigen die Arbeit.", stat1: "100%", stat2: "Entlastungs- & Konformitätsgarantie" },
    services: { subtitle: "Unsere Expertise", title: "End-to-End Sourcing-Lösungen", viewAll: "Alle Optionen anzeigen",
      s1: { title: "Custom Made Produktion", desc: "Komplett auf Ihre Markenrichtlinien zugeschnitten. Vom exakten Pantone™ PMS Abgleich bis hin zur Materialwahl.", longTitle: "Im Detail: Von der Vision zum greifbaren Ergebnis.", longDesc: "Bei H&O Worldwide glauben wir daran, dass Standardlösungen selten die Essenz einer Premium-Marke treffen. Unser 'Custom Made' Ansatz beginnt damit, die DNA Ihrer Marke zu verstehen. Wir arbeiten nicht mit Katalog-Standardartikeln, sondern entwerfen Produkte von Grund auf neu.\n\nDies bedeutet die exakte Übereinstimmung mit Ihren Pantone™ PMS-Farben für ein weltweit konsistentes Markenimage. Wir beraten Sie proaktiv bei der Materialverwendung – von nachhaltigen rPET-Stoffen bis hin zu hochwertigem, gebürstetem Metall – um das gewünschte taktile Erlebnis zu schaffen, das Ihrer Marktpositionierung entspricht. Ihre Markenrichtlinien sind unsere Blaupause für jedes Detail, von den Nähten bis zur Verpackung." },
      s2: { title: "Strategische Hubs", desc: "Unsere Kernbereiche: Türkei für hochwertige Textilien und schnelles Near-Shoring, China für Tech-Gadgets und Skaleneffekte.", longTitle: "Im Detail: Globale Reichweite, lokale Expertise.", longDesc: "Unsere Logistikinfrastruktur basiert auf zwei Säulen: Geschwindigkeit und Skalierbarkeit.\n\nTürkei (Premium Textilien & Geschwindigkeit): Unsere Drehkreuze in der Türkei sind auf hochwertige Textilien spezialisiert. Dank der geografischen Nähe zu Europa bieten wir hier 'ultra-schnelles Near-Shoring' an. Dies ermöglicht es uns, komplexe Textilprojekte in Rekordzeit zu produzieren und zu liefern, ideal für zeitkritische Kampagnen.\n\nChina (Technik & Skalierbarkeit): Für technologische Innovationen und riesige Volumina nutzen wir unsere etablierten Partnerschaften in China. Hier erzielen wir maximale Skaleneffekte für Tech-Gadgets und komplexe Hardware, ohne Kompromisse bei den strengsten Qualitätskontrollen einzugehen.\n\nDurch diese Hybridstrategie bieten wir immer die effizienteste Route für Ihr spezifisches Projekt." },
      s3: { title: "Full-Service Logistik", desc: "Nach der Produktion kümmern wir uns um Qualitätskontrolle, Zollabfertigung, Lagerung und die Endauslieferung (Last-Mile).", longTitle: "Im Detail: Komplette Entlastung, von der Fabrik bis zum Schreibtisch.", longDesc: "Produktion ist nur die halbe Miete; die wahre Herausforderung liegt in der Ausführung. H&O nimmt Ihnen die volle operative Last von den Schultern. Sobald die Produktion abgeschlossen ist, beginnt unser integrierter Logistikprozess:\n\nQualitätskontrolle (QC): Unabhängige Inspektionen vor Ort, bevor überhaupt etwas versendet wird.\n\nZoll & Compliance: Wir erledigen alle Zollformalitäten, Einfuhrzölle und die komplexe Dokumentation.\n\nLagerung: Bei Bedarf lagern wir Ihren Bestand sicher in unseren strategischen Vertriebszentren.\n\nLast-Mile Delivery: Egal, ob an ein zentrales Distributionszentrum oder an 500 einzelne Büroadressen weltweit geliefert wird: Wir sorgen dafür, dass das Paket zur richtigen Zeit in den richtigen Händen ankommt." },
      s4: { title: "Qualität & Ethik", desc: "Absolute Konformitätssicherheit. Alle Partnerwerke erfüllen strenge EU-Normen (inkl. CE) und bestehen Audits.", longTitle: "Im Detail: Integrität als Fundament.", longDesc: "In der heutigen Geschäftswelt ist Compliance keine Option, sondern eine absolute Notwendigkeit. Wir schützen Ihren guten Ruf, indem wir nur mit Fabriken zusammenarbeiten, die die höchsten ethischen und technischen Standards erfüllen.\n\nUnsere gesamte Hardware ist CE-zertifiziert und entspricht den strengsten EU-Sicherheitsnormen (z. B. RoHS und REACH). Darüber hinaus durchlaufen unsere Partnerfabriken regelmäßige Sozialaudits (wie Sedex oder BSCI), um faire Arbeitsbedingungen, Arbeitssicherheit und umweltbewusste Produktionsprozesse zu gewährleisten. Bei H&O Worldwide erhalten Sie also nicht nur ein Premium-Produkt, sondern auch die uneingeschränkte Sicherheit, dass es mit Respekt für Mensch und Umwelt produziert wurde." }
    },
    nodes: { title: "Strategische Sourcing-Nodes", desc: "Wählen Sie das Lieferkettenkonzept, das zu Ihrer Mission passt.",
      tr: { title: "Hub Türkei", features: ["Fokus: Nachhaltige Mode & Textilien", "Transport: LKW (Umweltfreundlicher)", "Lieferzeit: 2-3 Wochen", "Spezialität: Geschwindigkeit & Near-Shoring"] },
      cn: { title: "Hub China", features: ["Fokus: Tech-Gadgets & Volumen", "Transport: See- & Luftfracht", "Lieferzeit: 8-12 Wochen", "Spezialität: Skalierung & Kosteneffizienz"] }
    },
    journey: { title: "Die H&O Journey", desc: "Unsere lückenlose Logistik-Pipeline von A bis Z.",
      steps: [
        { title: "Konzeptionelles Design", desc: "Übersetzung der Markenidentität in physische Prämien." },
        { title: "Node Routing", desc: "Wahl des strategischen Hubs (Türkei vs. China)." },
        { title: "Produktion & QC", desc: "Ethische Fertigung mit strengen AQL-Inspektionen." },
        { title: "Last-Mile Delivery", desc: "Zollabfertigung und Lieferung bis vor die Tür." }
      ]
    },
    cases: { subtitle: "Portfolio", title: "Premium-Lösungen, greifbar gemacht", 
      items: [
        { title: "Executive Onboarding Experience", desc: "Luxuriöse 'Welcome-to-the-team'-Pakete, die die Corporate Identity nahtlos in einen greifbaren Moment der Wertschätzung für neue Talente übersetzen.", longDesc: "Entwickelt für hochrangige Partner, die einen unvergesslichen ersten Eindruck hinterlassen möchten. Diese Executive-Boxen enthalten Premium-Notizbücher im Moleskine-Stil, hochwertige Schreibgeräte und personalisierte Tech-Essentials wie maßgeschneiderte Powerbanks. Jedes Element wird sorgfältig ausgewählt, um die Werte und Professionalität Ihrer Kanzlei widerzuspiegeln – komplett betreut vom Design bis zur Distribution." },
        { title: "Premium Tech Event Solutions", desc: "Nachhaltige Markenaktivierung für den Tech-Sektor: Hochwertige rPET-Rucksäcke kombiniert mit zertifizierter, innovativer Hardware.", longDesc: "Machen Sie Eindruck auf Ihrem nächsten Event mit Swag, der wirklich genutzt wird. Wir kombinieren ökologisch verantwortungsvolle rPET-Rucksäcke mit erstklassigen, CE-zertifizierten kabellosen Schnellladegeräten. Unser Full-Service-Ansatz garantiert die direkte Lieferung an den Veranstaltungsort, wobei technische Perfektion und Nachhaltigkeit Hand in Hand gehen. Ideal für große internationale Tech-Konferenzen, bei denen Qualität der Standard ist." },
        { title: "National Brand Activation", desc: "Großserienproduktion und blitzschnelle 'Fast-Track'-Lieferung von Markenaktivierungs-Kits für landesweite Marketingkampagnen.", longDesc: "Maximieren Sie Ihre Marktdurchdringung mit hochwertigen Konsumgütern. Für diesen Fall lieferten wir Volumenprojekte aus maßgeschneiderten Frotteehandtüchern und Premium-Kühltaschen. Dank unserer strategischen Produktionszentren in der Türkei garantieren wir eine extrem kurze Time-to-Market, selbst bei Volumina von 10.000+ Einheiten. Wir managen die gesamte Kette: vom Pantone-Matching bis zur abschließenden Last-Mile-Lieferung an Ihre Distributoren." }
      ]
    },
    why: { title: "Die H&O Garantie", desc: "Warum uns große Player ihren Einkaufs- und Vertriebsprozess anvertrauen.",
      features: [
        { title: "Komplette Entlastung", desc: "Wir eliminieren Komplexität. Keine Sorgen über Zölle, Mängel oder Kommunikation. Ihr dedizierter SPOC.", longTitle: "Im Detail: Ihr engagierter Partner in einer komplexen Welt.", longDesc: "Der Beschaffungsprozess von Custom Merchandise ist oft ein Minenfeld aus logistischen Herausforderungen und bürokratischem Aufwand. H&O fungiert als Ihr Schutzschild. Wir übernehmen die volle Verantwortung für den gesamten Ablauf: vom ersten Entwurf und der Qualitätskontrolle in der Fabrik bis hin zur Organisation komplexer Einfuhrzölle und Zollformalitäten.\n\nSie müssen sich keine Sorgen über Mängel oder Missverständnisse mit Lieferanten in anderen Zeitzonen machen. Als Ihr Single Point of Contact (SPOC) bieten wir volle Transparenz und Sicherheit, damit Sie sich auf Ihr Kerngeschäft konzentrieren können, während wir die greifbaren Ergebnisse liefern." },
        { title: "Transparente Skaleneffekte", desc: "Keine Zwischenhändler. Unser Direkteinkauf garantiert Ihnen die besten Beschaffungsraten.", longTitle: "Im Detail: Direkte Einkaufskraft ohne versteckte Kosten.", longDesc: "Große Volumina erfordern einen scharfen Blick auf die Kostenstruktur. Da H&O die traditionellen Zwischenhändler (wie Agenten und lokale Großhändler) eliminiert, kaufen Sie direkt an der Quelle. Wir bündeln unsere Einkaufsvolumina strategisch, um die besten Beschaffungsbedingungen für unsere Kunden durchzusetzen.\n\nDiese Effizienz übersetzen wir in ein transparentes Preismodell. Keine versteckten Margen beim Transport oder unklare Aufschläge für die Zollabfertigung. Sie profitieren von der Größe eines Global Players mit der persönlichen Betreuung einer Boutique-Agentur. Wir beweisen, dass Premium-Qualität und ein gesundes Geschäftsergebnis hervorragend zusammenpassen." },
        { title: "Europäische Konformität", desc: "Von CE-Zeichen für Elektronik bis hin zu BSCI-zertifizierter Kleidung garantieren wir 100%ige Sicherheit.", longTitle: "Im Detail: Sicherheit für Ihre Marke und Ihren Endverbraucher.", longDesc: "Nichts ist für eine Marke so schädlich wie ein unsicheres Produkt oder eine ethisch fragwürdige Produktionskette. Die H&O-Garantie bedeutet, dass jedes von uns gelieferte Produkt der strengsten europäischen Gesetzgebung entspricht.\n\nOb es um die elektrische Sicherheit eines Ladegeräts (CE-Kennzeichnung), die Abwesenheit von Schadstoffen in Textilien (REACH/OEKO-TEX) oder die sozialen Bedingungen in der Fabrik (BSCI/Sedex-Audits) geht: Wir liefern Ihrer Einkaufsabteilung 100%ige Sicherheit. Wir führen unabhängige Tests durch, um zu garantieren, dass die gelieferte Qualität exakt mit dem genehmigten Muster übereinstimmt. Die Integrität Ihrer Marke ist bei uns in sicheren Händen.", showBadges: true },
        { title: "Geschwindigkeit (Near-Shoring)", desc: "Durch unsere türkischen Textilhubs sind wir in der Lage, bei Markttrends besonders schnell zu agieren.", longTitle: "Im Detail: Agilität in einem sich wandelnden Markt.", longDesc: "In der modernen Marketingwelt ist 'Geschwindigkeit' oft der entscheidende Erfolgsfaktor. Lange Wartezeiten aus Asien sind nicht immer eine Option, wenn Sie sofort auf einen Markttrend oder ein Last-Minute-Event reagieren wollen.\n\nUnser strategischer Fokus auf Near-Shoring über unsere türkischen Textilhubs ermöglicht es uns, die Durchlaufzeiten drastisch zu verkürzen. Während der Seetransport aus Fernost Wochen dauert, können wir über den Straßentransport aus der Türkei innerhalb weniger Tage in die Benelux-Staaten liefern. Dies gibt Ihnen die Flexibilität, reaktionsschneller zu sein, die Lagerbestände niedrig zu halten und schneller zu agieren, ohne Kompromisse bei der Qualität der Verarbeitung einzugehen." }
      ]
    },
    break: "Skalierbare Lösungen. Keine Kompromisse.",
    contact: { ready: "Bereit, Ihre Lieferkette zu vereinfachen?", title: "Heben Sie Ihr Corporate Gifting an.", desc: "Kontaktieren Sie unsere Account-Manager, um zu besprechen, wie H&O Worldwide Ihre Werbeeffizienz steigern kann.", quote: "Musterpaket Anfragen", call: "Kontaktiere Uns" },
    footer: { desc: "H&O Worldwide Solutions ist Ihr B2B-Partner für Custom Sourcing, ethische Produktion und komplette Merchandise-Logistik.", menu: "Navigation", offices: "Operative Hubs", hq: "Hauptsitz EU", privacy: "Datenschutz & Cookies", certs: "Konformitätsgarantie durch:" },
    cookie: { title: "Wir respektieren Ihre Privatsphäre", desc: "Wir verwenden essenzielle Cookies, damit unsere Seite funktioniert. Für Analysen nutzen wir optionale Cookies. Ablehnen setzt nur die notwendigen Cookies.", accept: "Alle Akzeptieren", reject: "Optionale Ablehnen" }
  },
  ES: {
    nav: { about: "Sobre Nosotros", services: "Servicios", why: "¿Por qué H&O?", cases: "Portafolio", quote: "Cotización" },
    hero: { spoc: "Tu Socio en Logística y Merchandising", p1: "H&O Worldwide ", p2: "optimiza", p3: " la visibilidad de tu marca.", desc: "Diseñamos y producimos soluciones de merchandising de alta gama mientras nos hacemos cargo de toda la cadena logística. Eficiencia para marcas premium.", quote: "Solicitar Cotización", samplePack: "Solicitar Paquete de Muestra", discover: "Descubrir los beneficios" },
    about: { title: "De la gran idea a un producto físico premium, sin estrés.", p1: "Las grandes organizaciones no necesitan un catálogo estándar. Buscan un socio estratégico que traduzca su identidad en productos tangibles.", p2: "A través de diseñadores expertos y potentes hubs de producción en Turquía y China, aseguramos soluciones estéticamente perfectas, escalables y acordes a las normas internacionales.", p3: "Tomamos el control total de la cadena. Tú diriges, nosotros hacemos el trabajo.", stat1: "100%", stat2: "Garantía de Cumplimiento" },
    services: { subtitle: "Nuestra Experiencia", title: "Soluciones de Adquisición End-to-End", viewAll: "Ver Todas las Opciones",
      s1: { title: "Producción a Medida", desc: "Totalmente adaptado a tu marca. Desde colores Pantone™ PMS exactos hasta materiales elegidos para posicionamiento premium.", longTitle: "En Detalle: De la visión al resultado tangible.", longDesc: "En H&O Worldwide, creemos que las soluciones estándar rara vez capturan la esencia de una marca premium. Nuestro enfoque 'Hecho a Medida' comienza por comprender el ADN de su marca. No trabajamos con artículos estándar de catálogo, sino que construimos los productos desde cero.\n\nEsto significa coincidir exactamente con sus colores Pantone™ PMS para una imagen de marca consistente en todo el mundo. Asesoramos de forma proactiva sobre el uso de materiales, desde telas duraderas de rPET hasta metal cepillado de alta calidad, para crear la experiencia táctil deseada que se alinee con su posicionamiento en el mercado. Las pautas de su marca son nuestro modelo para cada detalle, desde las costuras hasta el embalaje." },
      s2: { title: "Hubs Estratégicos", desc: "Nuestras áreas clave: Turquía para textiles premium y near-shoring ultra rápido, China para gadgets tecnológicos y máximas economías de escala.", longTitle: "En Detalle: Alcance global, experiencia local.", longDesc: "Nuestra infraestructura logística se basa en dos pilares: agilidad y escala.\n\nTurquía (Textiles Premium y Velocidad): Nuestros centros en Turquía se especializan en textiles de alta calidad. Debido a la proximidad geográfica con Europa, aquí ofrecemos un 'near-shoring ultrarrápido'. Esto nos permite producir y entregar proyectos textiles complejos en un tiempo récord, ideal para campañas urgentes.\n\nChina (Tecnología y Escala): Para innovaciones tecnológicas y grandes volúmenes, aprovechamos nuestras asociaciones establecidas en China. Es aquí donde obtenemos economías de escala máximas para dispositivos tecnológicos y hardware complejo, sin comprometer los controles de calidad más estrictos.\n\nA través de esta estrategia híbrida, siempre ofrecemos la ruta más eficiente para su proyecto en particular." },
      s3: { title: "Logística Integral", desc: "Compenetración es la clave. Después de la producción, gestionamos aduanas, almacenaje y entrega de última milla.", longTitle: "En Detalle: Alivio completo, de la fábrica a la oficina.", longDesc: "La producción es sólo la mitad de la historia; el verdadero desafío está en la ejecución. H&O le quita de encima toda la carga operativa. Una vez que se completa la producción, comienza nuestro proceso de logística integrada:\n\nControl de Calidad (QC): Inspecciones independientes en el sitio antes de enviar nada en absoluto.\n\nAduanas y Cumplimiento: Nos encargamos de todos los trámites aduaneros, derechos de importación y documentación compleja.\n\nAlmacenaje: Si es necesario, almacenamos su inventario de forma segura en nuestros centros de distribución estratégicos.\n\nEntrega Final: Ya sea que se entregue a un centro de distribución o a 500 direcciones de oficinas individuales en todo el mundo: nos aseguramos de que el paquete llegue a las manos adecuadas en el momento adecuado." },
      s4: { title: "Calidad y Ética", desc: "Certeza de cumplimiento absoluto. Fábricas conformes a las más altas normas de la UE (incluido CE) con auditorías sociales.", longTitle: "En Detalle: La integridad como cimiento.", longDesc: "En el mundo empresarial actual, el cumplimiento no es una opción, sino un requisito. Protegemos su reputación al asociarnos únicamente con fábricas que cumplen con los más altos estándares técnicos y éticos.\n\nTodo nuestro hardware cuenta con la certificación CE completa y cumple con los estándares de seguridad más estrictos de la UE (como RoHS y REACH). Además, nuestras fábricas asociadas se someten a auditorías sociales periódicas (como Sedex o BSCI) para garantizar condiciones de trabajo justas, seguridad en el lugar de trabajo y procesos de producción ambientalmente responsables. Con H&O Worldwide, no solo obtiene un producto de primera calidad, sino también la absoluta certeza de que se produce respetando a las personas y al planeta." }
    },
    nodes: { title: "Nodos de Adquisición Estratégicos", desc: "Elige el modelo logístico que se adapte a tu misión.",
      tr: { title: "Hub Turquía", features: ["Enfoque: Moda Sostenible y Textiles", "Transporte: Camión (Más ecológico)", "Plazo: 2-3 semanas", "Especialidad: Velocidad y Near-Shoring"] },
      cn: { title: "Hub China", features: ["Enfoque: Tecnología y Volumen", "Transporte: Marítimo y Aéreo", "Plazo: 8-12 semanas", "Especialidad: Escala y Eficiencia"] }
    },
    journey: { title: "El Camino H&O", desc: "Nuestra ejecución de logística integral de A-Z.",
      steps: [
        { title: "Diseño Conceptual", desc: "Traduciendo la identidad en premios corporativos." },
        { title: "Enrutamiento", desc: "Eligiendo el hub estratégico (Turquía vs China)." },
        { title: "Producción y Calidad", desc: "Fabricación ética y rigor en auditorías AQL." },
        { title: "Entrega Final", desc: "Trámites aduaneros y entrega directa al destino." }
      ]
    },
    cases: { subtitle: "Portafolio", title: "Soluciones de clase mundial, palpables", 
      items: [
        { title: "Executive Onboarding Experience", desc: "Lujosos paquetes 'Welcome-to-the-team' que traducen a la perfección la identidad corporativa en un momento tangible de aprecio para el nuevo talento.", longDesc: "Diseñados para socios de alto nivel que buscan una primera impresión inolvidable. Estas cajas ejecutivas contienen cuadernos premium estilo Moleskine, artículos de escritura de alta calidad y elementos tecnológicos esenciales personalizados como powerbanks a medida. Cada elemento se selecciona cuidadosamente para reflejar los valores y el profesionalismo de su firma, con una gestión total desde el diseño hasta la distribución." },
        { title: "Premium Tech Event Solutions", desc: "Activación de marca sostenible para el sector tecnológico: mochilas de rPET de alta calidad combinadas con hardware innovador certificado.", longDesc: "Cause impacto en su próximo evento con obsequios (swag) que realmente se utilicen. Combinamos mochilas de rPET ecológicamente responsables con cargadores rápidos inalámbricos de primer nivel y certificación CE. Nuestro enfoque de servicio completo garantiza la entrega directa en el lugar del evento, uniendo la perfección técnica con la sostenibilidad. Ideal para conferencias tecnológicas internacionales a gran escala donde la calidad es la norma." },
        { title: "National Brand Activation", desc: "Producción a gran escala y entrega ultrarrápida 'fast-track' de kits de activación de marca para campañas de marketing a nivel nacional.", longDesc: "Maximice su penetración en el mercado con productos de consumo de alta calidad. Para este caso, entregamos proyectos en gran volumen de toallas de tela de rizo personalizadas y bolsas refrigeradoras premium. Gracias a nuestros centros de producción estratégicos en Turquía, garantizamos un tiempo de comercialización extremadamente corto, incluso con volúmenes de más de 10.000 unidades. Gestionamos toda la cadena: desde la igualación de colores Pantone hasta la entrega final de última milla a sus distribuidores." }
      ]
    },
    why: { title: "La Promesa H&O", desc: "Por qué las principales marcas nos confían sus pedidos.",
      features: [
        { title: "Liberación Total a Tu Servicio", desc: "Eliminamos lo complejo. Sin preocupaciones sobre aduanas o defectos de comunicación. Tu socio SPOC dedicado.", longTitle: "En detalle: Su socio dedicado en un mundo complejo.", longDesc: "El proceso de adquisición de productos personalizados es a menudo un campo minado de desafíos logísticos y burocracia. H&O actúa como su escudo. Asumimos la plena responsabilidad de todo el proceso: desde el diseño inicial y el control de calidad en la fábrica hasta la gestión de complejos derechos de importación y trámites aduaneros.\n\nNo tiene que preocuparse por defectos o falta de comunicación con proveedores en otras zonas horarias. Como su único punto de contacto (SPOC), ofrecemos total transparencia y tranquilidad, para que pueda concentrarse en sus actividades principales mientras entregamos resultados tangibles." },
        { title: "Transparencia Económica", desc: "Sin intermediarios, asegurando que pagas tarifas directas y agrupadas desde fábrica.", longTitle: "En detalle: Poder adquisitivo directo sin costes ocultos.", longDesc: "Los grandes volúmenes requieren un ojo avizor en la estructura de costos. Debido a que H&O elimina a los intermediarios tradicionales (como agentes y mayoristas locales), usted compra directamente de la fuente. Agrupamos estratégicamente nuestros volúmenes de compras para imponer las condiciones de adquisición más estrictas para nuestros clientes.\n\nTraducimos esta eficiencia en un modelo de precios transparente. Sin márgenes ocultos en el transporte ni recargos poco claros para el despacho de aduanas. Se beneficia de la escala de un jugador global con la atención personal de una agencia boutique. Demostramos que la calidad superior y una línea de fondo saludable pueden ir de la mano a la perfección." },
        { title: "Conformidad Europea, Siempre", desc: "Hacemos que tu compra sea 100% libre de riesgos desde marcaje CE de electrónicos a textiles BSCI.", longTitle: "En detalle: Seguridad para su marca y su usuario final.", longDesc: "Nada es tan perjudicial para una marca como un producto inseguro o una cadena de producción éticamente dudosa. La Garantía H&O significa que cada producto que entregamos cumple con la legislación europea más estricta.\n\nYa sea que se trate de la seguridad eléctrica de un cargador (marcado CE), la ausencia de sustancias nocivas en los textiles (REACH/OEKO-TEX) o las condiciones sociales en la fábrica (auditorías BSCI/Sedex): entregamos 100% de seguridad a su departamento de compras. Llevamos a cabo pruebas independientes para garantizar que la calidad entregada coincida exactamente con la muestra aprobada. La integridad de su marca está en buenas manos con nosotros.", showBadges: true },
        { title: "Agilidad en Near-Shoring Mundial", desc: "Las tendencias cambian; nosotros nos adaptamos velozmente desde nuestros centros en Turquía para escalar.", longTitle: "En detalle: Agilidad en un mercado cambiante.", longDesc: "En el mundo del marketing moderno, la 'velocidad' es a menudo el factor determinante para el éxito. Los largos tiempos de espera de Asia no siempre son una opción cuando desea responder de inmediato a una tendencia del mercado o un evento de última hora.\n\nNuestro enfoque estratégico en el Near-Shoring a través de nuestros centros textiles turcos nos permite reducir drásticamente los tiempos de entrega. Si bien el transporte marítimo desde el Lejano Oriente lleva semanas, podemos realizar entregas en el Benelux en unos pocos días a través del transporte por carretera desde Turquía. Esto le brinda la flexibilidad de ser más receptivo, mantener bajos los niveles de inventario y moverse más rápido sin comprometer la calidad del acabado." }
      ]
    },
    break: "Soluciones escalables. Cero compromisos.",
    contact: { ready: "¿Listo para optimizar tu cadena de suministro?", title: "Eleva los regalos de tu empresa.", desc: "Habla con nuestros Asesores Senior sobre cómo potenciar tu impacto promocional en toda el área logística.", quote: "Solicitar Muestra", call: "Contactar Ahora" },
    footer: { desc: "H&O Worldwide Solutions es tu aliado estratégico global en aprovisionamiento y producción B2B a la medida.", menu: "Navegación", offices: "Centros Operativos", hq: "Zonal de la Unión Europea", privacy: "Privacidad y Cookies", certs: "Cumplimiento certificado por:" },
    cookie: { title: "Respetamos tu privacidad", desc: "Utilizamos cookies estrictamente necesarias para operar y cookies opcionales para fines analíticos.", accept: "Aceptar Todo", reject: "Rechazar Opcionales" }
  }
};
